apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "nginx:latest"
          ports:
            - name: backend
              containerPort: 84
