apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator
  namespace: dev

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: pod-creator
  namespace: dev
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
